
data_paths:
  cmu_plot_summaries: /home/student/project/data/plot_summaries.txt
  cmu_metadata: /home/student/project/data/movie.metadata.tsv
  wiki: /home/student/project/data/wiki_movie_plots_deduped.csv
  full_dataset: /home/student/project/data/full_dataset.csv
  filtered_dataset: /home/student/project/data/filtered_dataset.csv
  filtered_dataset_3_30: /home/student/project/data/filtered_dataset_3_30.csv

dataset:
  train_prcnt: 0.85
  test_prcnt: 0.075

T5:
  model_name: t5-base
  run_ds: filtered_dataset_3_30
  input_cols: ['Title', 'new_genres']
#  input_cols: ['Title', 'new_genres', 'kw_kb_1']
  model_save_path: /home/student/project/model1902
  min_len: 3
  max_len: 30

  train_args:
#    output_dir: results
    overwrite_output_dir: True
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    save_strategy: 'epoch'
#    metric_for_best_model: eval_loss  #FIXME: change to the metric of the article
#    greater_is_better: True  #FIXME - according to metric
    evaluation_strategy: 'epoch'
    do_train: True
    num_train_epochs: 12
    report_to: 'wandb'

## Config for debugging
#  train_args:
##    output_dir: results
#    overwrite_output_dir: True
#    per_device_train_batch_size: 1
#    per_device_eval_batch_size: 1
#    save_strategy: 'no'
##    metric_for_best_model: eval_loss  #FIXME: change to the metric of the article
##    greater_is_better: True  #FIXME - according to metric
#    evaluation_strategy: 'epoch'
#    do_train: True
#    num_train_epochs: 1
#    report_to: 'none'

w_and_b:
  project: NLP_project_PlotGenerator
  entity: nlp_final_project
  group: run2
  job_type: rake
  mode: online