
data_paths:
  cmu_plot_summaries: /home/student/project/data/plot_summaries.txt
  cmu_metadata: /home/student/project/data/movie.metadata.tsv
  wiki: /home/student/project/data/wiki_movie_plots_deduped.csv


training_args:
  epochs: 100
  lr: 1e-5
